- platform: rest
  resource: "https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/demande.json"
  name: Demande de puissance réseau Hydro-Québec
  unique_id: hydro_quebec_demande_puissance_total
  json_attributes:
  unit_of_measurement: MW
  device_class: power
  state_class: measurement
  verify_ssl: true
  ssl_cipher_list: intermediate
  value_template: >
   {% set index =  value_json.indexDonneePlusRecent %}
   {{ value_json.details[index]["valeurs"]["demandeTotal"] }}
