sensor:
  - platform: rest
    resource: "https://www.tvanouvelles.ca/api/schools/closed"
    name: "Écoles Fermées data"
    unique_id: ecoles_fermees_data
    value_template: 'OK'
    json_attributes:
      - result
      - lastUpdated
    scan_interval: 1800

template:
  - sensors:
    - name: École Saint-René
      unique_id: ecole_1267_fermeture
      state: >
        {% set school_id = 1267 %}
        {% set value_json = (state_attr('sensor.ecoles_fermees_data', 'result')) %}
        {% set schools = (value_json.institutions | selectattr('id', 'equalto', school_id) | list) %}
        {% set school = schools[0] if schools else None %}
        {% if school and school.closures %}
         {% set latest_closure = school.closures | first %}
         {% if latest_closure.datetime_start <= now().isoformat() and latest_closure.datetime_end >= now().isoformat() %}
           Fermée
         {% else %}
           Ouverte
         {% endif %}
        {% else %}
           Ouverte
        {% endif %}
      icon: >
        {% if is_state('sensor.ecole_1267_fermeture', 'Fermée')  %}
          mdi:snowman
        {% elif is_state('sensor.ecole_1267_fermeture', 'Ouverte')  %}
          mdi:townhall
        {% endif %}
      attributes:
        message: >
          {% set school_id = 1267 %}
          {% set value_json = (state_attr('sensor.ecoles_fermees_data', 'result')) %}
          {% set schools = (value_json.institutions | selectattr('id', 'equalto', school_id) | list) %}
          {% set school = schools[0] if schools else None %}
          {% if school and school.closures %}
            {% set latest_closure = school.closures | first %}
            {% if latest_closure.datetime_start <= now().isoformat() and latest_closure.datetime_end >= now().isoformat() %}
                {{ latest_closure.message }}
            {% endif %}
          {% endif %}
        information: >
          {% set school_id = 1267 %}
          {% set value_json = (state_attr('sensor.ecoles_fermees_data', 'result')) %}
          {% set schools = (value_json.institutions | selectattr('id', 'equalto', school_id) | list) %}
          {% set school = schools[0] if schools else None %}
          {% if school and school.closures %}
            {% set latest_closure = school.closures | first %}
            {% if latest_closure.datetime_start <= now().isoformat() and latest_closure.datetime_end >= now().isoformat() %}
                {{ latest_closure.closure_informations | map(attribute='name') | list | tojson }}
            {% endif %}
          {% endif %}
        last_updated: >
          {% set date_string = (state_attr('sensor.ecoles_fermees_data', 'lastUpdated')) %}
          {% set date_format = "%d-%m-%Y %H:%M:%S" %}
          {{ strptime(date_string, date_format) }}
        attribution: Données fournies par TVA Nouvelles
